version: "3.8"
services:
    # webapp:
    #     restart: 'no'
    #     build: 
    #         context: ./webapp/.
    #     ports:
    #         - "8080:8080"

    # flaskapp:
    #     build: ./flaskapp/.
    #     ports:
    #         - "5000:5000"

    # redis-server:
    #     image: "redis:alpine"

    # mariadb:
    #     image: mariadb
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=topsecret
    #         - MYSQL_DATABASE=vindb

    # db1:
    #     image: 'mysql:5.7'
    #     volumes:
    #         - db_data: /var/lib/mysql
    #     restart: always
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=topsecret
    #         - MYSQL_DATABASE=wordpress
    #         - MYSQL_USER=wordpress
    #         - MYSQL_PASSWORD=wordpress

    # wordpress:
    #     depends_on: 
    #         - db1
    #     image: wordpress:latest
    #     ports:
    #         - "80:80"
    #     restart: always
    #     environment: 
    #         WORDPRESS_DB_HOST: "db"
    #         WORDPRESS_DB_USER: wordpress
    #         WORDPRESS_DB_PASSWORD: wordpress
# services:
    mysql:
        container_name: flask_mysql
        restart: always
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
            MYSQL_USER: 'test'
            MYSQL_PASS: 'pass'
        volumes:
            - my-datavolume:/var/lib/mysql
volumes:
    my-datavolume: