version: '3'

volumes: 
    db_data:
    wordpress_data:

services:
    # container-1
    mysql:
        image: 'mysql:5.7'
        volumes: 
            - db_data=/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=wordpress
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress

    # container-2
    wordpress:
        image: wordpress:latest
        volumes: 
            - wordpress_data=/var/www/html
        depends_on: 
            - mysql
        ports: 
            - "3000:80"
        environment: 
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpress
