FROM alpine:latest

ENTRYPOINT [ "cal" ]
CMD ["7", "2020" ]

# docker build -t learnwithvinod/cal .     
# docker run learnwithvinod/cal   
# docker run learnwithvinod/cal 2020
# docker run learnwithvinod/cal 1 1974